# Generated by Django 3.1.1 on 2020-10-01 09:39

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('post', '0004_auto_20201001_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
