# Generated by Django 3.1.1 on 2020-10-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20201001_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='image',
            field=models.ImageField(upload_to='Sorlphoto/%Y', verbose_name='IMAGE'),
        ),
    ]
