# Generated by Django 3.1.1 on 2020-10-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20201002_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='image',
            field=models.ImageField(upload_to='photo/%Y/%m', verbose_name='IMAGE'),
        ),
    ]
