# Generated by Django 3.1.1 on 2020-10-02 13:27

from django.db import migrations
import photo.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20201002_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='image',
            field=photo.fields.ThumbnailImageField(upload_to='photo/%Y/%m', verbose_name='IMAGE'),
        ),
    ]
