# Generated by Django 3.1.1 on 2020-09-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-upload_dt',)},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-upload_dt',)},
        ),
        migrations.AddField(
            model_name='album',
            name='upload_dt',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='UPLOAD DATE'),
            preserve_default=False,
        ),
    ]
