# Generated by Django 3.1.1 on 2020-09-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20200927_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='album',
            name='upload_dt',
        ),
    ]
