# Generated by Django 3.1.1 on 2020-09-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20200927_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('title',)},
        ),
    ]
