# Generated by Django 3.1.1 on 2020-09-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20200927_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='upload_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='UPLOAD DATE'),
        ),
    ]
