# Generated by Django 3.1.1 on 2020-09-29 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_auto_20200929_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='upload_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='UPLOAD DATE'),
        ),
    ]
