# Generated by Django 3.1.1 on 2020-09-29 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import photo.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0011_auto_20200929_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='NAME'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.album'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, verbose_name='Photo Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=photo.fields.ThumbnailImageField(upload_to='photo/%Y/%m', verbose_name='IMAGE'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=30, verbose_name='TITLE'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='UPLOAD DATE'),
        ),
    ]
